### ISSUE TITLE
KinoAOC should trim the input

### ISSUE THREAD

**Issue by Malian** [ljgago/kino_aoc#1]
I encounter an issue with the Day 6 of AdventCalendar 2022. I spent several hours to find the issue ^^ It seems that KinoAOC trim the content of the input. Unfortunately, I won't work if the beginning of the content is a space, and if this space is relevant for the challenge.

Example:
```
                [B]     [L]     [S]
        [Q] [J] [C]     [W]     [F]
    [F] [T] [B] [D]     [P]     [P]
    [S] [J] [Z] [T]     [B] [C] [H]
    [L] [H] [H] [Z] [G] [Z] [G] [R]
[R] [H] [D] [R] [F] [C] [V] [Q] [T]
[C] [J] [M] [G] [P] [H] [N] [J] [D]
[H] [B] [R] [S] [R] [T] [S] [R] [L]
 1   2   3   4   5   6   7   8   9
```
Is not the same as:
```
[B]     [L]     [S]
        [Q] [J] [C]     [W]     [F]
    [F] [T] [B] [D]     [P]     [P]
    [S] [J] [Z] [T]     [B] [C] [H]
    [L] [H] [H] [Z] [G] [Z] [G] [R]
[R] [H] [D] [R] [F] [C] [V] [Q] [T]
[C] [J] [M] [G] [P] [H] [N] [J] [D]
[H] [B] [R] [S] [R] [T] [S] [R] [L]
 1   2   3   4   5   6   7   8   9
```
I believe that removing the trim here (https://github.com/ljgago/kino_aoc/blob/main/lib/kino_aoc.ex#L11) will solve the issue.

I'll propose a patch when I will have time. Feel free to go ahead.

**Comment by ljgago** [comment]
Hi, I added the trim in the last update because in the last line there is always an extra \n, I think that should removes it

**Comment by ljgago** [comment]
The trim was removed, remove the cache for update or add `force: true` in the Mix.install for use it.

**Comment by Malian** [comment]
It works like a charm :heart:
